version: "3.8"

services:
  php:
    build: ./docker
    volumes:
      - .:/var/www/html
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
      - XDEBUG_CONFIG=${XDEBUG_CONFIG:-client_host=host.docker.internal}
  phpunit:
    build: ./docker
    entrypoint: ["php", "./vendor/bin/phpunit"]
    volumes:
      - .:/var/www/html
  phpstan:
    build: ./docker
    entrypoint: [ "php", "./vendor/bin/phpstan", "--memory-limit=-1" ]
    volumes:
      - .:/var/www/html
  composer:
    build: ./docker
    entrypoint: ["composer"]
    volumes:
      - .:/var/www/html
