blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/Propaganistas/Laravel-Phone/blob/master/.github/macroable.md
    about: 'The PhoneNumber class is macroable to support whatever you need. If you feel that something might be useful for others, please open a pull request.'
